// 2021/09-九月份/复习react/day03/shopping-cart/src/components/CartList/index.jsx
import React from "react";
function CartList(props) {
    // 删除
    const handleDelete = (id) => {
        props.deleteItem(id)
    }
    const handleSub = (id) => {
        props.changeItem({
            type: 'sub',
            id: id
        })
    }
    const handleAdd = (id) => {
        props.changeItem({
            type: 'add',
            id: id
        })
    }
    const handleChange = (id, e) => {
        props.changeItem({
            type: 'change',
            id: id,
            num: e.target.value
        })
    }
    return (
        <div>
            {props.list.map(item => (
                <div className="item" key={item.id}>
                    <img src={item.img} />
                    <div className="name">{item.name}</div>
                    <div className="change">
                        <a href="#" onClick={() => handleSub(item.id)}>－</a>
                        <input type="text" className="num" value={item.num} onChange={(e) => handleChange(item.id, e)} />
                        <a href="#" onClick={() => handleAdd(item.id)}>＋</a>
                    </div>
                    <div className="del" onClick={() => handleDelete(item.id)}>×</div>
                </div>
            ))
            }
        </div>
    )
}
export default CartList

// 2021/04-四月份/TypeScript-day05/shoppingCart/src/components/CartList/index.vue
<template>
	<!-- 列表 -->
	<div>
		<div class="item" v-for="item in productList" :key="item.id">
			<img :src="item.img" />
			<div class="name">{{ item.name }}</div>
			<div class="change">
				<a href="" @click.prevent="sub(item.id)">－</a>
				<input
					type="text"
					class="num"
					:value="item.num"
					@blur="handleChangeProduct($event, item.id)"
				/>
				<a href="" @click.prevent="add(item.id)">＋</a>
			</div>
			<div class="del" @click="handleDeleteProduct($event, item.id)">×</div>
		</div>
	</div>
</template>

<script lang='ts'>
import { defineComponent } from "vue";
export default defineComponent({
	props: {
		productList: {
			type: Array,
			required: true,
		},
	},
	setup(props, { emit }) {
		// 删除
		const handleDeleteProduct = function (event: MouseEvent, id) {
			emit("del", id);
		};
		const handleChangeProduct = function (event: any, id) {
			if (event.target.value < 0) {
				alert("输入的值不能为负数");
				return;
			}
			emit("change-num", {
				id: id,
				type: "change",
				num: event.target.value,
			});
		};
		const add = function (id) {
			emit("change-num", {
				id: id,
				type: "add",
			});
		};
		const sub = function (id) {
			emit("change-num", {
				id: id,
				type: "sub",
			});
		};
		return {
			handleDeleteProduct,
			handleChangeProduct,
			add,
			sub,
		};
	},
});
</script>

<style>
</style>
