// 2022/3-三月份/day04-React/react-demo/src/传送门组件/Modal.js
import React from 'react'
import ReactDOM from 'react-dom'
function Modal() {
    return ReactDOM.createPortal(
        <div style={{ width: '100%', height: '100%', position: 'fixed', left: 0, top: 0, background: "rgba(0,0,0,0.5)" }}>
            <div style={{ width: 400, height: 400, background: '#fff', position: 'absolute', left: '50%', top: '50%', marginLeft: -200, marginTop: -200 }}>Modal</div>
        </div>,
        document.getElementById('root1')
    )
}

export default Modal

// 2021/11-十一月份/Vue3/day02/demo/src/components/Modal.vue
<!-- Modal.vue -->
<template>
  <div class="wrapper">
    <div class="content">
      <a class="close" href="javascript:">关闭</a>
    </div>
  </div>
</template>
<script>
export default {
  name: "Modal",
};
</script>
<style scoped>
.wrapper {
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.4);
}
.content {
  width: 660px;
  height: 400px;
  background: white;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}
.close {
  position: absolute;
  right: 10px;
  top: 10px;
  color: #999;
  text-decoration: none;
}
</style>
