// 2021/09-九月份/复习react/day03/shopping-cart/src/components/CartList/index.jsx
import React from "react";
function CartList(props) {
    // 删除
    const handleDelete = (id) => {
        props.deleteItem(id)
    }
    const handleSub = (id) => {
        props.changeItem({
            type: 'sub',
            id: id
        })
    }
    const handleAdd = (id) => {
        props.changeItem({
            type: 'add',
            id: id
        })
    }
    const handleChange = (id, e) => {
        props.changeItem({
            type: 'change',
            id: id,
            num: e.target.value
        })
    }
    return (
        <div>
            {props.list.map(item => (
                <div className="item" key={item.id}>
                    <img src={item.img} />
                    <div className="name">{item.name}</div>
                    <div className="change">
                        <a href="#" onClick={() => handleSub(item.id)}>－</a>
                        <input type="text" className="num" value={item.num} onChange={(e) => handleChange(item.id, e)} />
                        <a href="#" onClick={() => handleAdd(item.id)}>＋</a>
                    </div>
                    <div className="del" onClick={() => handleDelete(item.id)}>×</div>
                </div>
            ))
            }
        </div>
    )
}
export default CartList

// 2020/10-十月份/day10-vue/cart/src/components/cartList.vue
<template>
  <div>
    <div class="item" v-for="item in list" :key="item.id">
      <img :src="item.img" />
      <div class="name">{{ item.name }}</div>
      <div class="change">
        <a href="" @click.prevent="sub(item.id)">－</a>
        <input
          type="text"
          class="num"
          :value="item.num"
          @blur="change(item.id, $event)"
        />
        <a href="" @click.prevent="add(item.id)">＋</a>
      </div>
      <div class="del" @click="$emit('del', item.id)">×</div>
    </div>
  </div>
</template>

<script>
export default {
  props: ["list"],
  methods: {
    change(id, event) {
      if (event.target.value < 0) {
        event.target.value = 0;
      }
      this.$emit("changenum", {
        id: id,
        type: "change",
        num: event.target.value
      });
    },
    add(id) {
      this.$emit("changenum", {
        id: id,
        type: "add"
      });
    },
    sub(id) {
      this.$emit("changenum", {
        id: id,
        type: "sub"
      });
    }
  }
};
</script>

<style>
</style>
