// 2020/10-十月份/day10-vue/cart/src/components/cartTotal.vue
<template>
  <div class="total">
    <span>总价：{{ price }}</span>
    <button>结算</button>
  </div>
</template>

<script>
export default {
  props: ["list"],
  // 计算总价
  computed: {
    price() {
      let sum = 0;
      this.list.forEach(ele => {
        sum += ele.num * ele.price;
      });
      return sum;
    }
  }
};
</script>

<style>
</style>

// 2021/06-六月份/day05-redux/shopping-cart/src/components/CartTotal/index.jsx
import React from 'react';
function CartTotal(props) {
  // 定义一个方法，计算总价
const  calcPrice = () => {
    let sum = 0;
    props.list.forEach(item => {
      sum += item.price * item.num
    });
    return sum
  }
    return (
      <div className="total">
        <span>总价：{calcPrice()}</span>
        <button>结算</button>
      </div>
    )
}
export default CartTotal
