// 2021/05-五月份/day03-react/shopping-cart/src/components/CartTotal/index.jsx
import React from 'react';
class CartTotal extends React.Component {
  // 定义一个方法，计算总价
  calcPrice = () => {
    let sum = 0;
    this.props.list.forEach(item => {
      sum += item.price * item.num
    });
    return sum
  }
  render() {
    return (
      <div className="total">
        <span>总价：{this.calcPrice()}</span>
        <button>结算</button>
      </div>
    )
  }
}
export default CartTotal

// 2020/10-十月份/day10-vue/cart2/src/components/cartTotal.vue
<template>
  <div class="total">
    <span>总价：{{ price }}</span>
    <button>结算</button>
  </div>
</template>

<script>
export default {
  props: ["list"],
  computed: {
    price() {
      let sum = 0;
      this.list.forEach(ele => {
        sum += ele.num * ele.price;
      });
      return sum;
    }
  }
};
</script>

<style>
</style>
