// 2021/06-六月份/day05-redux/shopping-cart/src/components/CartTotal/index.jsx
import React from 'react';
function CartTotal(props) {
  // 定义一个方法，计算总价
const  calcPrice = () => {
    let sum = 0;
    props.list.forEach(item => {
      sum += item.price * item.num
    });
    return sum
  }
    return (
      <div className="total">
        <span>总价：{calcPrice()}</span>
        <button>结算</button>
      </div>
    )
}
export default CartTotal

// 2021/04-四月份/TypeScript-day05/shoppingCart/src/components/CartTotal/index.vue
<template>
	<div class="total">
		<span>总价：{{ price }}</span>
		<button>结算</button>
	</div>
</template>

<script lang='ts'>
import { computed, defineComponent, ref } from "vue";
import "../../types/cc";
export default defineComponent({
	props: {
		productList: {
			type: Array,
			required: true,
		},
	},
	setup(props) {
		// console.log(props);
		const { productList } = props;
		const price = computed(() => {
			let sum = 0;
			productList.forEach((ele: productItem) => {
				sum += ele.num * ele.price;
			});
			return sum;
		});
		return {
			price,
		};
	},
});
</script>

<style>
</style>
